### PR TITLE
Fix Info#parse_warnings regex

### PR DESCRIPTION
**Pull request by lab-kw**
Fixed a case where the log could not be parsed correctly when there were multiple lines.
ImageMagick's identify log shows that the file size includes a decimal point and a unit prefix.

example:
```
PAM 800 800 2.23232MB
```

cf. prefixes
https://github.com/ImageMagick/ImageMagick/blob/6bcfc4813644ce1450b7ebc9b7cedbd0ff172d71/MagickCore/string.c#L1088

### CODE REVIEW

**Comment by midnight-wonderer** [comment]
What was `d*` for?

**Comment by lab-kw** [comment]
@midnight-wonderer It's my mistake. Thank you for pointing out.

**Comment by thiagofm** [comment]
Hey @lab-kw thanks for your contribution!

Could you add a test case for that?

Cheers.

**Comment by lab-kw** [comment]
@thiagofm 
I added a test case.
I have confirmed that this test now passes by fixing parse_warnings.


My environment (ImageMagick is installed by yum)
> Version: ImageMagick 6.9.10-68 Q16 x86_64 2021-10-14 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(3.1) 
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps rsvg tiff wmf x xml zlib

**Pull request merged**
