### PR TITLE
Info#details: Skip badly encoded lines

### PR DESCRIPTION
**Pull request by n0nick**
This avoids a total crash of MiniMagick when one of the lines in
ImageMagick's `identify -verbose` results is badly encoded (as might
happen for some input files).

### CODE REVIEW

**Comment by n0nick** [comment]
Woah, I'm not sure why the GraphicsMagick specs fail on Travis, they pass on my machine :/

**Comment by n0nick** [comment]
OK, looks like GraphicsMagick on the Travis machine is able to parse these values correctly:

```
"Software"=>"\\377\\012"
```

So I will skip the GraphicsMagick test for this bug. Unless you have a better idea?

**Comment by janko-m** [comment]
Yes, it's fine to skip GraphicsMagick for this, I already did that in another spec.

**Comment by janko-m** [comment]
Thanks a lot for the patch!

**Comment by n0nick** [comment]
NP, thanks for being so responsive! :)

**Comment by n0nick** [comment]
I don't mean to put any pressure - but do you think you'll be able to push a new version in the upcoming days? I want to update a product with this bugfix. Thanks!

**Comment by janko-m** [comment]
I would like to release a new version as soon as I fix https://github.com/minimagick/minimagick/issues/340.

**Comment by n0nick** [comment]
Alright, thanks :)

**Pull request merged**
