### PR TITLE
Move from Travis CI to GitHub CI

### PR DESCRIPTION
**Pull request by janko**

### CODE REVIEW

**Comment by janko** [comment]
Ah, it seems I need bigger permissions for this repository in on order for GitHub CI to be activated, which I failed to get due to lack of response from the previous owner 😞

**Comment by janko** [comment]
@bensie @HamptonMakes @probablycorey @thiagofm Could one of you make me the **owner** of the MiniMagick repo/organization, so that I can replace Travis CI with GitHub Actions? 🙏🏻 

I've been maintaining MiniMagick for many years now, so I would like to be able make changes like removing the dead RubyForge link.

**Comment by HamptonMakes** [comment]
You're like....

MAINTAINERS OF THE PAST---- I SUMMON THEEEEEEEEEEE FROM THE NETHER REALMS!!!!!!

Give me a minute to poke around. :)

**Comment by bensie** [comment]
@janko Done! 🤗

**Comment by bensie** [comment]
@HamptonMakes @janko Look at how quick we come out of the woodwork!

**Comment by HamptonMakes** [comment]
_/_/_/_/_/  _/    _/  _/_/_/_/     _/_/    _/        _/_/_/   
   _/      _/    _/  _/         _/    _/  _/        _/    _/  
  _/      _/_/_/_/  _/_/_/     _/    _/  _/        _/    _/   
 _/      _/    _/  _/         _/    _/  _/        _/    _/    
_/      _/    _/  _/_/_/_/     _/_/    _/_/_/_/  _/_/_/       
                                                              
                                                              
                                                              
     _/_/    _/      _/  _/_/_/_/    _/_/_/                   
  _/    _/  _/_/    _/  _/        _/                          
 _/    _/  _/  _/  _/  _/_/_/      _/_/                       
_/    _/  _/    _/_/  _/              _/                      
 _/_/    _/      _/  _/_/_/_/  _/_/_/                         
                                                              
                                                              
                                                              
      _/_/_/    _/_/    _/      _/                            
   _/        _/    _/    _/  _/    _/                         
    _/_/    _/_/_/_/      _/                                  
       _/  _/    _/      _/                                   
_/_/_/    _/    _/      _/      _/                            
                                                              
                                                              
   _/  _/                                                     
  _/  _/  _/_/_/  _/_/_/_/_/    _/_/_/    _/_/_/              
           _/        _/          _/    _/                     
          _/        _/          _/      _/_/                  
         _/        _/          _/          _/                 
      _/_/_/      _/        _/_/_/  _/_/_/                    
                                                              
                                                              
                                                   _/  _/     
    _/_/_/      _/_/    _/      _/  _/_/_/_/  _/  _/  _/      
   _/    _/  _/    _/  _/_/    _/  _/        _/               
  _/    _/  _/    _/  _/  _/  _/  _/_/_/    _/                
 _/    _/  _/    _/  _/    _/_/  _/                           
_/_/_/      _/_/    _/      _/  _/_/_/_/  _/

**Comment by janko** [comment]
@HamptonMakes Haha, yeah, exactly 😁 

@bensie Thank you, really appreciate that! ❤️ 

Thank you both for such a quick turnaround 🙏🏻

**Comment by HamptonMakes** [comment]
IT IS DONE!@!!!!!!

(Lightning Strikes)
```
             zeeeeee-
            z$$$$$$"
           d$$$$$$"
          d$$$$$P
         d$$$$$P
        $$$$$$"
      .$$$$$$"
     .$$$$$$"
    4$$$$$$$$$$$$$"
   z$$$$$$$$$$$$$"
   """""""3$$$$$"
         z$$$$P
        d$$$$"
      .$$$$$"
     z$$$$$"
    z$$$$P
   d$$$$$$$$$$"
  *******$$$"
       .$$$"
      .$$"
     4$P"
    z$"
   zP
  z"
 / 
^
```

**Pull request closed without merging**
