### PR TITLE
Add feature to open remote images with Authorization token as wel

### PR DESCRIPTION
**Pull request by om-nishu-trantor**
Add feature to open remote images with Authorization token as wel

### CODE REVIEW

**Comment by om-nishu-trantor** [comment]
This fixes #349

**Comment by om-nishu-trantor** [comment]
minimagick_spec

All failures are : ```The command "sudo apt-get install -qq graphicsmagick" failed and exited with 100 during .```

**Comment by om-nishu-trantor** [comment]
@janko-m What do you think about the feature ?

**Comment by bensie** [comment]
@om-nishu-trantor thanks for taking the time to write up this implementation. Sadly this is far too specific of a use case for minimagick to handle. If you need to fetch an image with particular HTTP constraints, grab it with the HTTP client of your choice, then load it with ImageMagick.

**Comment by om-nishu-trantor** [comment]
We already have a feature of fetching remote images. This is just an addon
as remote images can be auth protected too. If the user fetches it first
then it will make user to take overhead of saving the image file first.
This feature is helping user to not do multiple images on system.

Thanks && Regards
Nishutosh

**Comment by bensie** [comment]
Images can be auth-protected in any number of ways - this addresses just one, and getting into setting HTTP header options for fetching is not a priority for MiniMagick.

**Comment by om-nishu-trantor** [comment]
I agree that there exists numerous ways to secure, thats why I chose OAuth bearer token to implement, as it is most widely used way MiniMagick can support, some other complex or sophisticated should not and cannot be a part of Image processing library :smiley:

**Pull request closed without merging**
